// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIG7RUp1k-YF4DgHrpEfNFdakbu_R7C3A',
    appId: '1:158685997295:web:3e454f6627f18221a3931a',
    messagingSenderId: '158685997295',
    projectId: 'spacex-go-8d74a',
    authDomain: 'spacex-go-8d74a.firebaseapp.com',
    storageBucket: 'spacex-go-8d74a.firebasestorage.app',
    measurementId: 'G-N7WLHKBFFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvMk3qkA6-gnH28a1yqMRd_TkEMx1i3DY',
    appId: '1:158685997295:android:d57e2af8207bb31ba3931a',
    messagingSenderId: '158685997295',
    projectId: 'spacex-go-8d74a',
    storageBucket: 'spacex-go-8d74a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPBphi8tIISZr-ajkuOFgNxTKlmqW4sI',
    appId: '1:158685997295:ios:ed3621b01a0ecd80a3931a',
    messagingSenderId: '158685997295',
    projectId: 'spacex-go-8d74a',
    storageBucket: 'spacex-go-8d74a.firebasestorage.app',
    iosClientId: '158685997295-uiscgore3574i8g5ivehctmta1idnfrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPBphi8tIISZr-ajkuOFgNxTKlmqW4sI',
    appId: '1:158685997295:ios:ed3621b01a0ecd80a3931a',
    messagingSenderId: '158685997295',
    projectId: 'spacex-go-8d74a',
    storageBucket: 'spacex-go-8d74a.firebasestorage.app',
    iosClientId: '158685997295-uiscgore3574i8g5ivehctmta1idnfrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIG7RUp1k-YF4DgHrpEfNFdakbu_R7C3A',
    appId: '1:158685997295:web:c861e0349f4fe985a3931a',
    messagingSenderId: '158685997295',
    projectId: 'spacex-go-8d74a',
    authDomain: 'spacex-go-8d74a.firebaseapp.com',
    storageBucket: 'spacex-go-8d74a.firebasestorage.app',
    measurementId: 'G-WQLJYCH2HJ',
  );

}